version: '3.4'

services:
    mssql-server:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "PatientDbpa55w0rd!"
            MSSQL_PID: "Express"
        ports:
          - "1433:1433"

    patientapi:
        image: ${DOCKER_REGISTRY-}patientapi
        build:
          context: ./PatientAPI/PatientAPI
          dockerfile: Dockerfile
        ports:
          - "8080:80"
          - "8081:443"
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_Kestrel__Certificates__Default__Password=PatientAPICertpa55w0rd!
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/PatientAPI.pfx
        volumes:
          - ~/.aspnet/https:/https:ro
        depends_on:
          - mssql-server